# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': (('test_course', '删除课程'),), 'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息表', 'verbose_name_plural': '客户信息表'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '校区信息表', 'verbose_name_plural': '校区信息表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '员工信息表', 'verbose_name_plural': '员工信息表'},
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='date',
            field=models.DateField(verbose_name='跟进日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='class_type',
            field=models.CharField(choices=[('online', '网络班'), ('offline_weekend', '面授班(周末)'), ('offline_fulltime', '面授班(脱产)')], default='offline_weekend', max_length=64, verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此客户是转介绍自内部学员,请在此处选择内部学员姓名', null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Customer', verbose_name='转介绍自学员'),
        ),
    ]
