# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '\u4f5c\u8005'},
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('published', '\u5df2\u51fa\u7248'), ('producing', '\u51fa\u7248\u4e2d'), ('forbidden', '\u7981\u4e66')], default='producing', max_length=32),
        ),
    ]
